language: java

cache:
  directories:
    - $HOME/.m2/repository

before_install:
# install IBM JDK8
  - JAVA_VER=8.0
  - JAVA_SR=3
  - JAVA_FP=0 
  - curl -sS -O https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.3.12/linux/x64/ibm-java-x86_64-sdk-8.0-3.12.bin
  - echo "USER_INSTALL_DIR=/opt/ibm/java" > installer.properties
  - echo "LICENSE_ACCEPTED=TRUE" >> installer.properties
  - chmod +x ibm-java-x86_64-sdk-8.0-3.12.bin
  - sudo ./ibm-java-x86_64-sdk-8.0-3.12.bin -i silent
env:
  global:
  - JAVA_HOME=/opt/ibm/java
  - PATH=$JAVA_HOME/bin:$PATH
  matrix:
   - COOKBOOK_PATH="https://github.com/chandrams/travis-cookbooks/tree/ibmjdk-travisci/cookbooks"
   
addons:
  apt:
    packages:
      - oracle-java6-installer

jdk:
  - oraclejdk8
# - oraclejdk7
# - oraclejdk9
# - ibmjdk8
  
script:
  - /opt/ibm/java/bin/java -version
  - echo $JAVA_HOME
  - echo $PATH
  - $JAVA_HOME/bin/javac hello/Hello.java
  - $JAVA_HOME/bin/java -showversion hello.Hello
  - javac hello/Hello.java
  - java -showversion hello.Hello
  - ls -l /usr/lib/jvm
