language: java

jdk:
  - oraclejdk8

  
script:
  - ls -la /usr/lib/jvm  
  - javac hello/Hello.java
  - java -showversion hello.Hello
  - which java
  - ls -l /etc/alternatives
  - ls -l /usr/bin
  - jdk_switcher use openjdk7
  - java -version
  - jdk_switcher use oraclejdk8
  - java -version



 