language: java

cache:
  directories:
    - $HOME/.m2/repository

env:
  global:
  
  matrix:
   - COOKBOOK_PATH="https://github.com/chandrams/travis-cookbooks/tree/ibmjdk-travisci/cookbooks"
   

jdk:
  - oraclejdk8
# - oraclejdk7
# - oraclejdk9
# - ibmjdk8
  
script:
  - ls -l /usr/lib/jvm
  - javac hello/Hello.java
  - java -showversion hello.Hello
  