language: java

jdk:
  - oraclejdk8

  
script:
  - ls -la /usr/lib/jvm  
  - javac hello/Hello.java
  - java -showversion hello.Hello
  - which java
  - jdk_switcher use ibmjava8
  - java -version
  - ls -l /etc/alternatives




 