language: java

matrix:
  include:
    - os: linux
      sudo: required
      group: edge
      jdk: ibmjava8

    - os: linux
      sudo: required
      group: edge
      jdk: oraclejdk8

  
script:
  - ls -l /usr/lib/jvm  
  - javac hello/Hello.java
  - java -showversion hello.Hello
  - which java
  



 